import type { NextPage } from 'next';
import Head from 'next/head';

//Map
import dynamic from 'next/dynamic';
const MapWithNoSSR = dynamic(() => import('../components/map'), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Inazuma</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link rel="shortcut icon" type="image/x-icon" href="public/favicon.ico" />
      </Head>
        <MapWithNoSSR/>
    </div>
  );
};

export default Home;

