import type { NextPage } from "next";
import Head from "next/head";

//Map
import dynamic from "next/dynamic";
import MapTable from "../components/map_DataTable";
const MapWithNoSSR = dynamic(() => import("../components/map"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Inazuma</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="public/favicon.ico"
        />
      </Head>
      <div className="flex justify-center items-center h-screen">
        <div className="w-1/3 mx-4">
          <MapTable />
        </div>
        <div className="w-1/4 mx-2">
          <MapWithNoSSR />
        </div>
      </div>
    </div>
  );
};

export default Home;
