import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import Footer from '../components/footer';


const Home: NextPage = () => {
  return (
    <div >
      {/* <Head>
        <title>CACAHACK</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link rel="shortcut icon" type="image/x-icon" href="public/favicon.ico" />
      </Head> */}
    </div>
  );
};

export default Home;

