import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Album from './Alubm';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CACAHACK</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="https://github.com/crypto0627/cacahack/blob/main/public/favicon.ico" rel="icon" />
      </Head>
        <Album/>  
    </div>
  );
};

export default Home;

